spring:
  application:
    name: spring-boot-rest-skeleton
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/mydatabase
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver

management.security.enabled: false
